var d = 9;
var r = 1 / 2;
var k = 2;
var er = 3.14;
var hasil = d / r;
document.write(" 12. Jari-jari (R) : 9 / 1/2 = ", hasil + "<br> ");
console.log(d / r);
var j = 7.5;
var hasil = er * j * j;
document.write(" Luas lingkaran (L): 3.14 * 7.5 * 7.5 =", hasil + "<br>");
console.log(er * j * j);
var hasil = k * er * r;
document.write(" Keliling lingkaran (K) : 2 * 3.14 * 1/2 =", hasil);
console.log(k * er * r);
